from PreguntaExamen import *

#Creación de objeto examen
examen = Examen()

#Creación de preguntas

#for i in range(1,31):
 #   print(f"p{i} = Pregunta(\"¿Pregunta número {i} de las 30 preguntas?\", \"Opción 1 (correcta)\", \"Opción 2 (incorrecta)\", \"Opción 3 (incorrecta)\")\nexamen.agregarP(p{i})")
 
p1 = Pregunta("¿Pregunta número 1 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p1)
p2 = Pregunta("¿Pregunta número 2 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p2)
p3 = Pregunta("¿Pregunta número 3 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p3)
p4 = Pregunta("¿Pregunta número 4 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p4)
p5 = Pregunta("¿Pregunta número 5 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p5)
p6 = Pregunta("¿Pregunta número 6 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p6)
p7 = Pregunta("¿Pregunta número 7 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p7)
p8 = Pregunta("¿Pregunta número 8 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p8)
p9 = Pregunta("¿Pregunta número 9 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p9)
p10 = Pregunta("¿Pregunta número 10 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p10)
p11 = Pregunta("¿Pregunta número 11 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p11)
p12 = Pregunta("¿Pregunta número 12 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p12)
p13 = Pregunta("¿Pregunta número 13 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p13)
p14 = Pregunta("¿Pregunta número 14 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p14)
p15 = Pregunta("¿Pregunta número 15 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p15)
p16 = Pregunta("¿Pregunta número 16 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p16)
p17 = Pregunta("¿Pregunta número 17 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p17)
p18 = Pregunta("¿Pregunta número 18 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p18)
p19 = Pregunta("¿Pregunta número 19 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p19)
p20 = Pregunta("¿Pregunta número 20 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p20)
p21 = Pregunta("¿Pregunta número 21 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p21)
p22 = Pregunta("¿Pregunta número 22 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p22)
p23 = Pregunta("¿Pregunta número 23 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p23)
p24 = Pregunta("¿Pregunta número 24 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p24)
p25 = Pregunta("¿Pregunta número 25 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p25)
p26 = Pregunta("¿Pregunta número 26 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p26)
p27 = Pregunta("¿Pregunta número 27 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p27)
p28 = Pregunta("¿Pregunta número 28 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p28)
p29 = Pregunta("¿Pregunta número 29 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p29)
p30 = Pregunta("¿Pregunta número 30 de las 30 preguntas?", "Opción 1 (correcta)", "Opción 2 (incorrecta)", "Opción 3 (incorrecta)")
examen.agregarP(p30)
